spring.application.name=movie-booking
spring.datasource.url=jdbc:mysql://localhost:3307/showbuddy
spring.datasource.username=root
spring.datasource.password=Aditya@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=ShowBuddySecretKeyForJWTTokenGeneration2026MustBeLongEnough
omdb.api.key=804d1408
razorpay.key.id=rzp_test_TF19BUzYYo8cjb
razorpay.key.secret=pmo1oCsBBE9M86QB8RprryKW